# Generated by Django 4.0.3 on 2022-04-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Live"), (2, "Replay")]),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.show",
                    ),
                ),
            ],
        ),
    ]
